// Therapist Export Package v1 — wrap a transcript in a therapist-friendly LOCAL folder.
//
// Guardrails (must hold): NO auto-generated clinical/SOAP notes, NO cloud/LLM, NO diagnosis/treatment/
// billing, NO HIPAA/medical/legal claims. The SOAP template ships BLANK (headings only). The transcript is
// the source of truth; the checklist only reminds the therapist to review/edit by hand. Everything is
// written locally to a folder the user chooses.
import * as fs from '@tauri-apps/plugin-fs'
import { path } from '@tauri-apps/api'

// --- Static templates (English; intentionally not auto-filled) ---

export const THERAPIST_REVIEW_CHECKLIST = `# Therapist Review Checklist

This app produced a raw transcript only. It does **not** generate clinical notes or analysis.
Please review and edit everything manually before using it.

- [ ] Review the transcript for accuracy (names, terms, numbers).
- [ ] Correct any misheard or mis-attributed speech.
- [ ] Remove anything that should not be retained.
- [ ] Add your own notes separately (see SOAP_Template_Blank.md if you use SOAP).
- [ ] Confirm the file is stored according to your own privacy/record-keeping practices.

Reminder: you are responsible for the content and handling of these files.
`

export const SOAP_TEMPLATE_BLANK = `# SOAP Note (blank template — fill in manually)

> This template is provided blank for your convenience. This application does **not** generate clinical
> notes, and nothing below is auto-filled or suggested. Complete it yourself based on your own judgment.

## Subjective


## Objective


## Assessment


## Plan

`

export const README_PRIVACY = `PrivateNote Therapist — Export Package (privacy reminder)

- These files are LOCAL to your computer. Nothing was uploaded; transcription runs on-device.
- This is a transcription tool, NOT a compliance product: it is not HIPAA-compliant, not medical-grade,
  not legally compliant, and not attorney-client privileged. It does not provide diagnosis, treatment,
  billing, or clinical-note automation.
- The transcript is the source of truth. Any notes (e.g. SOAP_Template_Blank.md) are yours to write manually.
- You are responsible for how you store, share, and handle these files per your own privacy and
  record-keeping practices.
`

// --- Types ---

export interface TherapistSessionInfo {
	sourceFileName?: string // synthetic/sample name only in beta
	modelName?: string
	dateTimeLabel: string // human-readable, e.g. "2026-07-05 14:30"
	transcriptFormat?: string // e.g. "plain text (normal)"
	durationLabel?: string // optional, if known
}

export interface TherapistPackageInput {
	transcript: string // plain-text transcript (source of truth)
	srt?: string | null // optional timed transcript
	session: TherapistSessionInfo
}

export interface TherapistPackageFiles {
	folderName: string
	files: Record<string, string>
}

// Two-digit zero pad.
function pad(n: number): string {
	return n < 10 ? `0${n}` : `${n}`
}

// Folder name: "PrivateNote Therapist Export - YYYY-MM-DD HHMM".
export function packageFolderName(now: Date): string {
	const y = now.getFullYear()
	const m = pad(now.getMonth() + 1)
	const d = pad(now.getDate())
	const hh = pad(now.getHours())
	const mm = pad(now.getMinutes())
	return `PrivateNote Therapist Export - ${y}-${m}-${d} ${hh}${mm}`
}

function sessionInfoText(s: TherapistSessionInfo): string {
	const lines = [
		'PrivateNote Therapist — Session Info',
		'',
		`Date/time: ${s.dateTimeLabel}`,
		`Source file: ${s.sourceFileName ?? '(not recorded)'}`,
		`Model: ${s.modelName ?? '(not recorded)'}`,
		`Transcript format: ${s.transcriptFormat ?? 'plain text (normal)'}`,
	]
	if (s.durationLabel) lines.push(`Duration: ${s.durationLabel}`)
	lines.push('', 'Note: factual session metadata only. No clinical content is generated by this app.')
	return lines.join('\n') + '\n'
}

// Pure builder — returns the folder name + the file map. No filesystem access (unit-testable).
export function buildTherapistPackageFiles(input: TherapistPackageInput, now: Date): TherapistPackageFiles {
	const files: Record<string, string> = {
		'Transcript.txt': input.transcript.endsWith('\n') ? input.transcript : input.transcript + '\n',
		'Session_Info.txt': sessionInfoText(input.session),
		'Therapist_Review_Checklist.md': THERAPIST_REVIEW_CHECKLIST,
		'SOAP_Template_Blank.md': SOAP_TEMPLATE_BLANK,
		'README_PRIVACY.txt': README_PRIVACY,
	}
	// Only include the timed transcript when timing is actually available.
	if (input.srt && input.srt.trim().length > 0) {
		files['Transcript.srt'] = input.srt.endsWith('\n') ? input.srt : input.srt + '\n'
	}
	return { folderName: packageFolderName(now), files }
}

// Create the package folder under `parentDir` and write all files. Returns the created folder path.
// Requires the `fs:allow-mkdir` capability (added in capabilities/main.json).
export async function exportTherapistPackage(parentDir: string, input: TherapistPackageInput, now: Date = new Date()): Promise<string> {
	const built = buildTherapistPackageFiles(input, now)
	const folderPath = await path.join(parentDir, built.folderName)
	await fs.mkdir(folderPath, { recursive: true })
	for (const [name, content] of Object.entries(built.files)) {
		const filePath = await path.join(folderPath, name)
		await fs.writeTextFile(filePath, content)
	}
	return folderPath
}
